[build]
builder = "NIXPACKS"
buildCommand = "pnpm api:build"

[deploy]
startCommand = "pnpm api:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
