export {
  BackIcon,
  BellIcon,
  BookmarkIcon,
  CameraIcon,
  CatalogTabIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CompareIcon,
  ContributionsIcon,
  DirectionsIcon,
  DiscoverTabIcon,
  DishIcon,
  FilterIcon,
  HeartIcon,
  Icon,
  LocationIcon,
  LocationPinIcon,
  MapIcon,
  PencilIcon,
  PhotosIcon,
  PlusIcon,
  ProfileTabIcon,
  RestaurantIcon,
  ReviewIcon,
  SavedTabIcon,
  SearchIcon,
  SettingsIcon,
  ShuffleIcon,
  XIcon,
  type IconComponentProps,
  type IconName,
  type IconProps,
} from './Icon';
